create table beer (menu_product_id bigint not null, category varchar(255), price double, name varchar(255), primary key (menu_product_id))
create table hibernate_sequences (sequence_name varchar(255) not null, sequence_next_hi_value bigint, primary key (sequence_name))
create table menu_product (menu_product_id bigint not null, category varchar(255), price double, primary key (menu_product_id))
create table order_table (order_id bigint generated by default as identity, order_number varchar(255), total double not null, primary key (order_id))
create table order_table_order_items (order_order_id bigint not null, order_items_order_item_id bigint not null)
create table order_item (order_item_id bigint generated by default as identity, total double not null, primary key (order_item_id))
create table order_item_product_list (order_item_order_item_id bigint not null, product_list_menu_product_id bigint not null)
create table pizza (menu_product_id bigint not null, category varchar(255), price double, pizza_base_menu_product_id bigint, primary key (menu_product_id))
create table pizza_toppings (pizza_menu_product_id bigint not null, toppings_topping_id bigint not null)
create table pizza_base (menu_product_id bigint not null, category varchar(255), price double, name varchar(255), primary key (menu_product_id))
create table topping (topping_id bigint generated by default as identity, name varchar(255), price double, primary key (topping_id))
alter table order_table_order_items add constraint FKsntcy1r707lrys9hqfxpyn9y foreign key (order_items_order_item_id) references order_item
alter table order_table_order_items add constraint FKgfllaey7uhsd3mav30lap0he6 foreign key (order_order_id) references order_table
alter table order_item_product_list add constraint FKt94efsa3gddm09faxphyeodip foreign key (order_item_order_item_id) references order_item
alter table pizza add constraint FK1wxc7ervv01y6d9hpbf6wbs2i foreign key (pizza_base_menu_product_id) references pizza_base
alter table pizza_toppings add constraint FKafbm9donijsj5rdpj9niy0bdw foreign key (toppings_topping_id) references topping
alter table pizza_toppings add constraint FKpyqbl50d9ajjc25xh7pmsko42 foreign key (pizza_menu_product_id) references pizza
